language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
script:
  - npm run test:ci
  - npm run test:coverage
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_AUTH_TOKEN
  app: groupffl-web
