export const FETCH_FANTASY_STANDINGS = 'FETCH_FANTASY_STANDINGS';
export const FETCH_FANTASY_STANDINGS_COMPLETE = 'FETCH_FANTASY_STANDINGS_COMPLETE';
export const FETCH_FANTASY_SCOREBOARD = 'FETCH_FANTASY_SCOREBOARD';
export const FETCH_FANTASY_SCOREBOARD_COMPLETE = 'FETCH_FANTASY_SCOREBOARD_COMPLETE';
